[project]
name = "fhirquestionnaire-mapper"
version = "0.1.0"
description = "Mapping and labeling FHIR Questionnaires"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fhir-resources>=7.1.0",
    "pydantic>=2.0",
    "fastapi>=0.100.0",
    "requests",
    "uvicorn",
    "google-auth",
    "python-dotenv",
    "fhir-sdc",
]

[tool.uv]
managed = true

[tool.uv.sources]
fhir-sdc = { git = "ssh://git@github.com/tiro-health/fhir-sdc-rs.git", tag = "v0.1.0-rc3" }

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.3",
]

